apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: api
  annotations:
    kubernetes.io/tls-acme: "true"
  generation: 1
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: api
    name: api
spec:
  ingressClassName: nginx
  rules:
  - host: api.ibm.prestodb.dev
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 3000
        pathType: ImplementationSpecific

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
  annotations:
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: deploy-infra-eks-managed-node-group-general
      containers:
      - name: api
        image: 093347738777.dkr.ecr.us-east-1.amazonaws.com/engprod/api:${BUILD_VERSION}
        ports:
        - containerPort: 3000
