apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
  labels:
    app: hive-metastore
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: hive-metastore
  ports:
    - name: tcp
      port: 9083
      protocol: TCP
      targetPort: 9083

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore-deployment
  namespace : hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: deploy-infra-eks-managed-node-group-general
      containers:
      - name: hive-metastore
        image: 093347738777.dkr.ecr.us-east-1.amazonaws.com/engprod/hms:3.1.3-20231009H23a46d7
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        ports:
        - containerPort: 9083
        command:
          - /bin/sh
          - /opt/entrypoint.sh
        env:
          - name: JDBC_MYSQL
            value: jdbc:mysql://${DEPLOY_MYSQL_HOST}/hive-metastore
          - name: DB_USER
            value: presto
          - name: DB_PASS
            value: ${DB_PASS}
          - name: AWS_ACCESS_KEY_ID
            value: ${AWS_ACCESS_KEY_ID}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${AWS_SECRET_ACCESS_KEY}
