kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-controller-pvc
  namespace: jenkins-controller
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 108Gi
