config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  presto-devx-infra:centos-stream-9-docker-ami: ami-02cbde25721bdbff1
  presto-devx-infra:hosted-zone-id: Z07061711IJOEXRXZEBV6
  presto-devx-infra:rds-mysql-password:
    secure: AAABALEeoj6jnUJQqtKJ5TS4TJ/EZBd/riV8I4Yj7ApFHiPwvsSFUtcX8IHZ/IbmjybIGMKdcVJLYBVwA8VEQWsEo167l0s0
  presto-devx-infra:ssh-ed25519-pubkey: AAAAC3NzaC1lZDI1NTE5AAAAIDnUFSamQY9c+RowwSW7gXnL36DK4k1gmSaeT14il+0r
